name: Deploy Front-end on AWS S3
on:
  push:
    branches:
      - main
    paths:
      - front-end/**
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
    steps:
      - uses: actions/checkout@v2

      - name: Checkout on front-end folder
        run: cd front-end

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build

      - name: Deploy
        uses: reggionick/s3-deploy@v3
        with:
          folder: dist
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          delete-removed: true
          no-cache: true
          private: true
